services:
  backend:
    build: ./backend
    volumes:
     - db-data:/app/data
    env_file: ".env"
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  
volumes:
  db-data:
    name: "server_statistics_db_data"