services:
  backend:
    build: ./backend
    volumes:
     - ./backend/data:/app/data
    environment:
      - DATABASE_PATH=/app/data/server_statistics.db
    env_file: ".env"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      args:
        VISIBLE_BACKEND_URI: ${VISIBLE_BACKEND_URI}
        VISIBLE_METRICS_SENDING_INTERVAL_SECONDS: ${VISIBLE_METRICS_SENDING_INTERVAL_SECONDS}
        VISIBLE_METRICS_RETAINING_TIME_DAYS: ${VISIBLE_METRICS_RETAINING_TIME_DAYS}
    env_file: ".env"
    ports:
      - "80:80"