name: server-statistics-dev

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
    - ./backend/:/app
    env_file: ".env"
    environment:
      - FRONTEND_URI=localhost:5173
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  frontend:
    env_file: ".env"
    environment:
      - VISIBLE_BACKEND_URI=localhost:8080
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy

  pimond:
    build: ./pimond
    env_file: ".env"
    environment:
    - BACKEND_URI=backend:8080
    volumes:
    - ./pimond/:/app
    depends_on:
      backend:
        condition: service_healthy