FROM golang:1.25.4-alpine3.22

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download
RUN air init

EXPOSE 8080

# Use air for hot-reload in development
CMD ["air"]